### ISSUE TITLE
Please provide installation instructions

### ISSUE THREAD

**Issue by igorshubovych** [porras/tlcr#2]
Please write instructions for installation.
That's what I got trying install shards in brew:

```
Last 15 lines from /Users/igor/Library/Logs/Homebrew/shards/01.crystal:

    parse(ARGV) { |parser| yield parser }
    ^~~~~

in ./src/cli.cr:23: instantiating 'OptionParser:Class#parse!()'

    OptionParser.parse! do |opts|
                 ^~~~~~

in ./src/cli.cr:24: undefined method 'working_directory' for Dir:Class

      path = Dir.working_directory
                 ^~~~~~~~~~~~~~~~~



READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/manastech/crystal/issues
```

**Comment by porras** [comment]
Hi!

Thanks for trying and reporting. I'm working in a simpler way to install that doesn't involve building from source or having to install crystal, but in case it helps: is that the output of `brew install shards`? I'm asking because in recent versions of crystal (and I don't think tlcr compiles with anything older than 0.10.0), shards is included and doesn't need to be installed separately. Please refer to http://crystal-lang.org/docs/installation/on_mac_osx_using_homebrew.html and tell me how it goes!

**Comment by igorshubovych** [comment]
Yes, this is output of 
`brew install shards`.

I installed Crystal from brew, it does not include shards. So maybe just add that link to installation instruction.
